version: '3.8'

services:
  web:
    build: .
    command: gunicorn main:app -b 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - FLASK_ENV=development